on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test

      - name: Build MSI
        run: dotnet build --configuration Release EQLogParserInstall\EQLogParserInstall.wixproj -o msi
          
      - name: Create Release
        uses: actions/upload-artifact@v4
        with:
          name: THJEQLogParser
          path: msi\en-us\EQLogParser.msi
